### ISSUE TITLE
Create Post Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#2]
**User story**:
As a user, I would like the ability to create a post

* persona: user who would like to create a post
* feature: user posts their item for sale on the website
* business value: necessary for a marketplace

**Task List**

- [ ] Make sure the database schemes handle storing of new listings
- [x] Create HTML view for creating posts 
- [x] The page should have the option to upload an image, make the name of the item, and give the listing a description
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. the user should be able to create a listing for their item

**Comment by Phi1lS** [comment]
TODO:
Remove "Contact Name" and "Contact Number" fields from the form
modify create_post.php to accomodate this. Also update it to store item names.

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
