### ISSUE TITLE
Change UI to Utilize Tailwind

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#24]
**User story**:
As a user, I would like a clean and simple UI

* persona: user who would like an easy-to-use and modern UI
* feature: user views a page utilizing modern UI elements
* business value: current website is an eyesore and a half

**Task List**

- [x] Update index.html to utilize Tailwind
- [x] Update login.html to utilize Tailwind
- [x] Update signup.html to utilize Tailwind
- [x] Update account_page.html to utilize Tailwind
- [x] Update settings.html to utilize Tailwind
- [x] Update purchases.html to utilize Tailwind
- [x] Update create_post.html to utilize Tailwind
- [x] Update checkout.html to utilize Tailwind
- [x] Update listing.html to utilize Tailwind (after issue #3 is complete)
- [x] Update all HTML files accordingly
- [x] Update all CSS files accordingly

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. UI should be simple yet intuitive
2. Navigation nor functionality of the website should not be hindered in any way
