### ISSUE TITLE
Listing Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#3]
**User story**:
As a user, I would like to see the other listings of users on the marketplace site as well as add that item to my cart.

* persona: user who would like to view a post
* feature: user views a detailed listing of an item for sale on the marketplace and can add to cart
* business value: makes it easier for end-user to decide whether an item is right for them

**Task List**

- [x] Make sure the database schemes handle storing of new listings
- [x] Create HTML view for viewing listings 
- [x] The page should display the item image, the name of the item, the description, and the poster of the listing
- [x] The add to cart function should add the item from the listing to the user's cart and should be connected to the database accordingly
- [x] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. the user should be view a listing for an item
2. the user should be able to add an item to their cart
