### ISSUE TITLE
Implement New Logo

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#32]
The new logo that Natalie made is pretty neat. I'm going to try and implement it properly in each of the pages with a logo.

**Task List**

- [x] Change pages to work with new logo
- [x] login.html
- [x] signup.html
- [x] index.html
- [x] create_post.html
- [x] account_page.html
- [x] purchases.html
- [x] settings.html
- [x] checkout.html

**Acceptance Criteria**
1. works on all modern web browsers
