### ISSUE TITLE
Create reviews page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#33]
**User story**:
As a user, I would like a clean and simple UI

* persona: user who would like an easy-to-use and modern UI
* feature: user views a page utilizing modern UI elements
* business value: current website is an eyesore and a half

**Task List**

- [x] Create a page called reviews.html that displays user reviews
- [x] #41
- [x] The header should be present in this page
- [x] A list of user reviews should be present in this page
- [x] The names of all reviewers lead to their respective account pages
- [x] Reviews are between 1 and 5 stars (no half stars)
- [x] #40
- [x] Submit review box should be on this page as well
- [x] Created in Tailwind

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. Reviews are displayed properly
2. Page is simple yet easy to access
