### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#4]
**User story**:
As a user, I would like an easy method to purchase all of the items that I have put in my cart.

* persona: user who would like to purchase the items in their cart
* feature: user views a page that shows cart items, allows user to select payment method, has button for checkout and confirmation
* business value: makes it easier for end-user to purchase an item

**Task List**

- [ ] Make sure the database schemes handle updating of purchased items
- [x] Create HTML view for checking out a user's cart
- [x] The page should display the items in the cart, options for a user's payment methods, and button for checkout and confirmation all on one page 
- [ ] The purchase function should update the items from the database to indication that they have been purchased. This can likely be done with a flag.
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. the user should be able to view all of the items in their cart, their payment methods with the option to change which one is used, a button for checkout, and a confirmation that the user would like to purchase.
2. the user should be able to purchase their items

**Comment by Phi1lS** [comment]
TODO:
Use PHP to store cart in purchases database after user has purchased an items so that they can access it from the Purchases page

Use PHP to retrieve user payment methods from database

Use PHP to retrieve cart and display it on the checkout page.

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
