### ISSUE TITLE
Account Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#5]
**User story**:
As a user, I would like an easy method to my account details as well as the details of other users.

* persona: user who would like to view account details
* feature: user views a page that shows account picture, user description, and user reviews. The page also allows the user to review users other than themself
* business value: makes it easier for end-user to trust other users

**Task List**

- [ ] Make sure the database schemes handle updating of new reviews and uploaded pfp
- [x] Create HTML view for the account page
- [x] The page should display the account's pfp, description, and reviews given to that account by other users. The page also allows the user to review that account
- [ ] If the current account page is that of the user, allow the user to change their pfp
- [x] We need a default user pfp
- [ ] The review function should add the reviews to the database
- [ ] The profilePicture function should update the profile picture in the database
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. the user should be able to view all of the items in their cart, their payment methods with the option to change which one is used, a button for checkout, and a confirmation that the user would like to purchase.
2. the user should be able to purchase their items

**Comment by Phi1lS** [comment]
TODO:
Add PHP to query the user's profile picture based on their primary key (user id) and display it dynamically with HTML
Use PHP to display User's name

Use PHP to check if user is viewing own account.
If so, allow user to upload image to update their profile picture
Also make it so that user cannot add reviews to their own account
Also allow user to change own description

Use PHP to display reviews from database
Use PHP to submit reviews to database

Use PHP to  display listings from database

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
