### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#6]
**User story**:
As a user, I would like an easy method to check and manage the settings of my account.

* persona: user who would like to view and modify account settings
* feature: user views a page that allows user to add, modify, remove payment information and address, or delete account
* business value: providing an easy approach for the end-user to access their payment information is essential to a marketplace website

**Task List**

- [ ] Make sure the database schemes handle CRUD of payment information or addresses, as well as account deletion
- [x] Create HTML view for the settings page
- [x] The page should display have a menu that allows the user to select between payment information, address information, and a button that allows a user to delete their account. For the account deletion button, a confirmation message must be displayed
- [x] We need a default user pfp
- [ ] The payment method function should perform CRUD to the database
- [ ] The address function should perform CRUD in the database
- [ ] The delete account function should delete the user's account from the database
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. the user should be able to choose between viewing and modifying payment methods, addresses, and deleting their account
2. The appropriate actions must be taken in the database

**Comment by Phi1lS** [comment]
TODO:
Need PHP code to retrieve user payment information from backend to display in frontend
Need PHP code to update user payment information in database
Need PHP code to retrieve user address information from backend to display in frontend
Need PHP code to update user address information in database
Need PHP code to delete user account upon confirmation in Delete Account

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
