### ISSUE TITLE
Purchases Page

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#7]
**User story**:
As a user, I would like an easy method to check and manage my purchases.

* persona: user who would like to view purchases
* feature: user views a page that allows user to view their purchases
* business value: providing an easy approach for the end-user to access their purchases is necessary for a marketplace website

**Task List**

- [x] Create HTML view for the purchases page
- [ ] The page should display a users purchases, which are retrieved from the database
- [ ] The display purchases function should perform read from a user's purchases in the database
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. The user should be able to view their purchases
2. The purchases are read from the database

**Comment by Phi1lS** [comment]
TODO: Individual purchase items will be inserted here via PHP and dynamically displayed with HTML

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
