### ISSUE TITLE
Cart UI Element

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#8]
**User story**:
As a user, I would like an easy way to check my cart

* persona: user who would like to view their cart
* feature: user clicks on a shopping cart icon that displays their current cart
* business value: providing an easy approach for the end-user to access their cart is necessary for a marketplace website

**Task List**

- [x] Create HTML view for the cart UI element
- [ ] The element consists of a drop-down menu filled with the user's current cart information, which is retrieved from the database
- [ ] The display cart function should perform read from a user's current cart in the database
- [ ] Cart information is stored in the database even after the user makes a purchase so that it can be viewed in the user's purchase history
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. The user should be able to view their cart
2. Perform CRUD for the cart from the database and store the cart information even after a user makes a purchase

**Comment by Phi1lS** [comment]
TODO:
In index.html:
Use PHP to read and display cart items in the dropdown menu Use PHP to check if there are cart items in the database. If there are none, display "No items are in your cart!" I have a temporary placeholder for now.

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
