### ISSUE TITLE
Account UI Element

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/ReMarket-471-Project#9]
**User story**:
As a user, I would like an easy way to access my account page, purchases, and settings

* persona: user who would like to view their account information
* feature: user clicks on an icon of their pfp that displays a drop-down menu containing links to their account page, their purchases, and the account settings page
* business value: providing an easy approach for the end-user to access their account information is necessary for a marketplace website

**Task List**

- [x] Create HTML view for the pfp UI element
- [x] The element consists of a drop-down menu filled with the options to view their account page, their purchases, and the account settings page
- [ ] The profile picture must be retrieved from the database

**Acceptance Criteria**
1. works on all modern web browsers

**Acceptance Tests**
1. The user should be able to view the account drop-down menu

**Comment by Phi1lS** [comment]
TODO:
Use PHP and HTML to dynamically adjust listings on homepage according to what is currently listed for sale Use PHP to retrieve user profile picture from database and use HTML to dynamically display it

**Comment by Phi1lS** [comment]
Closing this issue as we have separate issues for PHP scripts
